<?php
/*
 * Project Name: MiniManager for Mangos/Trinity Server
 * Date: 17.10.2006 inital version (0.0.1a)
 * Author: Q.SA
 * Copyright: Q.SA
 * Email: *****
 * License: GNU General Public License v2(GPL)
 */
define('CHAR_DATA_OFFSET_GENDER',22);
define('CHAR_DATA_OFFSET_HEALTH',23);
define('CHAR_DATA_OFFSET_MANA',24);
define('CHAR_DATA_OFFSET_RAGE',25);
define('CHAR_DATA_OFFSET_FOCUS',26);
define('CHAR_DATA_OFFSET_ENERGY',27);
define('CHAR_DATA_OFFSET_HAPPINESS',28);
define('CHAR_DATA_OFFSET_MAX_HEALTH',31);
define('CHAR_DATA_OFFSET_MAX_MANA',32);
define('CHAR_DATA_OFFSET_MAX_RAGE',33);
define('CHAR_DATA_OFFSET_MAX_FOCUS',34);
define('CHAR_DATA_OFFSET_MAX_ENERGY',35);
define('CHAR_DATA_OFFSET_MAX_HAPPINESS',36);
define('CHAR_DATA_OFFSET_LEVEL',53);
define('CHAR_DATA_OFFSET_MINDAMAGE',69); //cast
define('CHAR_DATA_OFFSET_MAXDAMAGE',70); //cast
define('CHAR_DATA_OFFSET_STR',84);
define('CHAR_DATA_OFFSET_AGI',85);
define('CHAR_DATA_OFFSET_STA',86);
define('CHAR_DATA_OFFSET_INT',87);
define('CHAR_DATA_OFFSET_SPI',88);
define('CHAR_DATA_OFFSET_ARMOR',99);
define('CHAR_DATA_OFFSET_RES_HOLY',100);
define('CHAR_DATA_OFFSET_RES_FIRE',101);
define('CHAR_DATA_OFFSET_RES_NATURE',102);
define('CHAR_DATA_OFFSET_RES_FROST',103);
define('CHAR_DATA_OFFSET_RES_SHADOW',104);
define('CHAR_DATA_OFFSET_RES_ARCANE',105);
define('CHAR_DATA_OFFSET_AP',123);
define('CHAR_DATA_OFFSET_RANGED_AP',126);
define('CHAR_DATA_OFFSET_MINRANGEDDAMAGE',129);
define('CHAR_DATA_OFFSET_MAXRANGEDDAMAGE',130);
define('CHAR_DATA_OFFSET_GUILD_ID',151);
define('CHAR_DATA_OFFSET_GUILD_RANK',152);
define('CHAR_DATA_OFFSET_EQU_HEAD',258);
define('CHAR_DATA_OFFSET_EQU_NECK',260);
define('CHAR_DATA_OFFSET_EQU_SHOULDER',262);
define('CHAR_DATA_OFFSET_EQU_SHIRT',264);
define('CHAR_DATA_OFFSET_EQU_CHEST',266);
define('CHAR_DATA_OFFSET_EQU_BELT',268);
define('CHAR_DATA_OFFSET_EQU_LEGS',270);
define('CHAR_DATA_OFFSET_EQU_FEET',272);
define('CHAR_DATA_OFFSET_EQU_WRIST',274);
define('CHAR_DATA_OFFSET_EQU_GLOVES',276);
define('CHAR_DATA_OFFSET_EQU_FINGER1',278);
define('CHAR_DATA_OFFSET_EQU_FINGER2',280);
define('CHAR_DATA_OFFSET_EQU_TRINKET1',282);
define('CHAR_DATA_OFFSET_EQU_TRINKET2',284);
define('CHAR_DATA_OFFSET_EQU_BACK',286);
define('CHAR_DATA_OFFSET_EQU_MAIN_HAND',288);
define('CHAR_DATA_OFFSET_EQU_OFF_HAND',290);
define('CHAR_DATA_OFFSET_EQU_RANGED',292);
define('CHAR_DATA_OFFSET_EQU_TABARD',294); 
define('CHAR_DATA_OFFSET_EXP',608);
define('CHAR_DATA_OFFSET_SKILL_DATA',610);
define('CHAR_DATA_OFFSET_BLOCK',998);
define('CHAR_DATA_OFFSET_DODGE',999);
define('CHAR_DATA_OFFSET_PARRY',1000);
define('CHAR_DATA_OFFSET_EXPERTISE',1001);
define('CHAR_DATA_OFFSET_OFFHAND_EXPERTISE',1002);
define('CHAR_DATA_OFFSET_CRIT',1003);
define('CHAR_DATA_OFFSET_RANGE_CRIT',1004);
define('CHAR_DATA_OFFSET_SPELL_CRIT_PER',1006);
define('CHAR_DATA_OFFSET_GOLD',1144);
define('CHAR_DATA_OFFSET_HONOR_KILL',1200);
define('CHAR_DATA_OFFSET_RESILIENCE',1620);
define('CHAR_DATA_OFFSET_HONOR_POINTS',1246);
define('CHAR_DATA_OFFSET_ARENA_POINTS',1247);
?>