<?php
/*
 * Project Name: MiniManager for Mangos Server
 * Date: 17.10.2006 inital version (0.0.1a)
 * Author: Q.SA
 * Copyright: Q.SA
 * Email: *****
 * License: GNU General Public License v2(GPL)
 */
define('CHAR_DATA_OFFSET_HEALTH',23);
define('CHAR_DATA_OFFSET_MANA',24); //POWER1
define('CHAR_DATA_OFFSET_LEVEL',53);
define('CHAR_DATA_OFFSET_GENDER',22); //BYTES_3
define('CHAR_DATA_OFFSET_MINDAMAGE',69); //cast
define('CHAR_DATA_OFFSET_MAXDAMAGE',70); //cast
define('CHAR_DATA_OFFSET_STR',84);
define('CHAR_DATA_OFFSET_AGI',85);
define('CHAR_DATA_OFFSET_STA',86);
define('CHAR_DATA_OFFSET_INT',87);
define('CHAR_DATA_OFFSET_SPI',88);
define('CHAR_DATA_OFFSET_ARMOR',99); //RESISTANCES
define('CHAR_DATA_OFFSET_RES_HOLY',100);
define('CHAR_DATA_OFFSET_RES_FIRE',101);
define('CHAR_DATA_OFFSET_RES_NATURE',102);
define('CHAR_DATA_OFFSET_RES_FROST',103);
define('CHAR_DATA_OFFSET_RES_SHADOW',104);
define('CHAR_DATA_OFFSET_RES_ARCANE',105);
define('CHAR_DATA_OFFSET_AP',123);
define('CHAR_DATA_OFFSET_RANGED_AP',126);
define('CHAR_DATA_OFFSET_MINRANGEDDAMAGE',129);
define('CHAR_DATA_OFFSET_MAXRANGEDDAMAGE',130);
define('CHAR_DATA_OFFSET_GUILD_ID',151);
define('CHAR_DATA_OFFSET_GUILD_RANK',152);
define('CHAR_DATA_OFFSET_EQU_HEAD',260);
define('CHAR_DATA_OFFSET_EQU_NECK',278);
define('CHAR_DATA_OFFSET_EQU_SHOULDER',296);
define('CHAR_DATA_OFFSET_EQU_SHIRT',314);
define('CHAR_DATA_OFFSET_EQU_CHEST',332);
define('CHAR_DATA_OFFSET_EQU_BELT',350);
define('CHAR_DATA_OFFSET_EQU_LEGS',368);
define('CHAR_DATA_OFFSET_EQU_FEET',386);
define('CHAR_DATA_OFFSET_EQU_WRIST',404);
define('CHAR_DATA_OFFSET_EQU_GLOVES',422);
define('CHAR_DATA_OFFSET_EQU_FINGER1',440);
define('CHAR_DATA_OFFSET_EQU_FINGER2',458);
define('CHAR_DATA_OFFSET_EQU_TRINKET1',476);
define('CHAR_DATA_OFFSET_EQU_TRINKET2',494);
define('CHAR_DATA_OFFSET_EQU_BACK',512);
define('CHAR_DATA_OFFSET_EQU_MAIN_HAND',530);
define('CHAR_DATA_OFFSET_EQU_OFF_HAND',548);
define('CHAR_DATA_OFFSET_EQU_RANGED',566);
define('CHAR_DATA_OFFSET_EQU_TABARD',584);
define('CHAR_DATA_OFFSET_EXP',1010);
define('CHAR_DATA_OFFSET_SKILL_DATA',1012);
define('CHAR_DATA_OFFSET_BLOCK',1400);
define('CHAR_DATA_OFFSET_DODGE',1401);
define('CHAR_DATA_OFFSET_PARRY',1402);
define('CHAR_DATA_OFFSET_CRIT',1405);
define('CHAR_DATA_OFFSET_RANGE_CRIT',1406);
define('CHAR_DATA_OFFSET_SPELL_CRIT_PER',1408);
define('CHAR_DATA_OFFSET_GOLD',1546);
define('CHAR_DATA_OFFSET_HONOR_KILL',1602);
define('CHAR_DATA_OFFSET_HONOR_POINTS',1648);
define('CHAR_DATA_OFFSET_ARENA_POINTS',1649);
?>