<?php
/*
 * Project Name: MiniManager for Mangos Server
 * Date: 17.10.2006 inital version (0.0.1a)
 * Author: Q.SA
 * Copyright: Q.SA
 * Email: *****
 * License: GNU General Public License v2(GPL)
 */
define('CHAR_DATA_OFFSET_HEALTH',28);
define('CHAR_DATA_OFFSET_MANA',29);
define('CHAR_DATA_OFFSET_LEVEL',34);
define('CHAR_DATA_OFFSET_GENDER',36);
define('CHAR_DATA_OFFSET_MINDAMAGE',148); //cast
define('CHAR_DATA_OFFSET_MAXDAMAGE',149); //cast
define('CHAR_DATA_OFFSET_STR',171);
define('CHAR_DATA_OFFSET_AGI',172);
define('CHAR_DATA_OFFSET_STA',173);
define('CHAR_DATA_OFFSET_INT',174);
define('CHAR_DATA_OFFSET_SPI',175);
define('CHAR_DATA_OFFSET_ARMOR',186);
define('CHAR_DATA_OFFSET_RES_HOLY',187);
define('CHAR_DATA_OFFSET_RES_FIRE',188);
define('CHAR_DATA_OFFSET_RES_NATURE',189);
define('CHAR_DATA_OFFSET_RES_FROST',190);
define('CHAR_DATA_OFFSET_RES_SHADOW',191);
define('CHAR_DATA_OFFSET_RES_ARCANE',192);
define('CHAR_DATA_OFFSET_AP',210);
define('CHAR_DATA_OFFSET_RANGED_AP',213);
define('CHAR_DATA_OFFSET_MINRANGEDDAMAGE',222);
define('CHAR_DATA_OFFSET_MAXRANGEDDAMAGE',223);
define('CHAR_DATA_OFFSET_GUILD_ID',237);
define('CHAR_DATA_OFFSET_GUILD_RANK',238);
define('CHAR_DATA_OFFSET_EQU_HEAD',346);
define('CHAR_DATA_OFFSET_EQU_NECK',362);
define('CHAR_DATA_OFFSET_EQU_SHOULDER',378);
define('CHAR_DATA_OFFSET_EQU_SHIRT',394);
define('CHAR_DATA_OFFSET_EQU_CHEST',410);
define('CHAR_DATA_OFFSET_EQU_BELT',426);
define('CHAR_DATA_OFFSET_EQU_LEGS',442);
define('CHAR_DATA_OFFSET_EQU_FEET',458);
define('CHAR_DATA_OFFSET_EQU_WRIST',474);
define('CHAR_DATA_OFFSET_EQU_GLOVES',490);
define('CHAR_DATA_OFFSET_EQU_FINGER1',506);
define('CHAR_DATA_OFFSET_EQU_FINGER2',522);
define('CHAR_DATA_OFFSET_EQU_TRINKET1',538);
define('CHAR_DATA_OFFSET_EQU_TRINKET2',554);
define('CHAR_DATA_OFFSET_EQU_BACK',570);
define('CHAR_DATA_OFFSET_EQU_MAIN_HAND',586);
define('CHAR_DATA_OFFSET_EQU_OFF_HAND',602);
define('CHAR_DATA_OFFSET_EQU_RANGED',618);
define('CHAR_DATA_OFFSET_EQU_TABARD',634);
define('CHAR_DATA_OFFSET_EXP',926);
define('CHAR_DATA_OFFSET_SKILL_DATA',928);
define('CHAR_DATA_OFFSET_BLOCK',1316);
define('CHAR_DATA_OFFSET_DODGE',1317);
define('CHAR_DATA_OFFSET_PARRY',1318);
define('CHAR_DATA_OFFSET_CRIT',1320);
define('CHAR_DATA_OFFSET_RANGE_CRIT',1321);
define('CHAR_DATA_OFFSET_SPELL_CRIT_PER',1323);
define('CHAR_DATA_OFFSET_GOLD',1397);
define('CHAR_DATA_OFFSET_HONOR_KILL',1453);
define('CHAR_DATA_OFFSET_HONOR_POINTS',1498);
define('CHAR_DATA_OFFSET_ARENA_POINTS',1499);
?>