<?php

define('EQ_DATA_OFFSET_EQU_HEAD',0);
define('EQ_DATA_OFFSET_EQU_NECK',2);
define('EQ_DATA_OFFSET_EQU_SHOULDER',4);
define('EQ_DATA_OFFSET_EQU_SHIRT',6);
define('EQ_DATA_OFFSET_EQU_CHEST',8);
define('EQ_DATA_OFFSET_EQU_BELT',10);
define('EQ_DATA_OFFSET_EQU_LEGS',12);
define('EQ_DATA_OFFSET_EQU_FEET',14);
define('EQ_DATA_OFFSET_EQU_WRIST',16);
define('EQ_DATA_OFFSET_EQU_GLOVES',18);
define('EQ_DATA_OFFSET_EQU_FINGER1',20);
define('EQ_DATA_OFFSET_EQU_FINGER2',22);
define('EQ_DATA_OFFSET_EQU_TRINKET1',24);
define('EQ_DATA_OFFSET_EQU_TRINKET2',26);
define('EQ_DATA_OFFSET_EQU_BACK',28);
define('EQ_DATA_OFFSET_EQU_MAIN_HAND',30);
define('EQ_DATA_OFFSET_EQU_OFF_HAND',32);
define('EQ_DATA_OFFSET_EQU_RANGED',34);
define('EQ_DATA_OFFSET_EQU_TABARD',36);

?>